# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
automation: !include_dir_list automations/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
# dev_pi: !include packages/dev_pi.yaml

homeassistant:
  customize: !include customize.yaml


# Text to speech ____________________________________

tts:
  - platform: google_translate
    base_url: !secret https_url


# Assistants Section _________________________________

google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include MyAssist.json
  report_state: true
  exposed_domains:
    - fan
    - climate
    - scene
    - light
  entity_config:
    input_boolean.ac_dumper:
      expose: true
      name: AC Dumper
    media_player.bedroom_tv:
      expose: true
      name: Bedroom TV
    media_player.samsung_65:
      expose: true
      name: Living Room TV
    media_player.receiver:
      expose: true
      name: Receiver
    switch.boiler_tuya:
      expose: true
      name: Boiler

alexa:
  smart_home:
    locale: en-US
    endpoint: https://api.amazonalexa.com/v3/events
    filter:
      include_domains:
        - light
        - fan
        - climate
        - camera
        - scene
      exclude_entities:
        - light.ceiling_light
      exclude_domains:
        - switch
        - media_player
      include_entities:
        - switch.boiler_tuya
        - input_boolean.ac_dumper
        - media_player.samsung_65
        - media_player.receiver
        - media_player.bedroom_tv
      
api:


# External Integration Section _________________________________

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key
  
sonoff:
  username: !secret yair_email
  password: !secret sonoff_password

yeelight:
  devices:
    !secret yeelight_ceiling_ip:
      name: Ceiling light
      model: ceiling13

bring_shopping_list:
  lists:
    - id: !secret bring_shopping_list_id
      name: Shopping
      locale: en-US
      
# localtuya:
#   - host: !secret local_tuya_host
#     device_id: !secret local_tuya_device_id
#     local_key: !secret local_tuya_local_key
#     friendly_name: Tuya Devices
#     protocol_version: "3.3"
#     entities:
#       - platform: switch
#         friendly_name: kitchen light
#         id: 1


# Home Assistant Components Section _________________________________

binary_sensor:
  - platform: workday
    country: ISR

input_boolean:
  bedroom_tv:
    name: Bedroom TV
    icon: mdi:television
  ac_dumper:
    name: AC Dumper
    icon: mdi:air-conditioner
  sat_sched:
    name: Sat Scheduler for summer
    icon: mdi:scheduler
  home_is_occupied:
    name: Home is occupied
    icon: mdi:home-account
  house_guests:
    name: House guests
    icon: mdi:account-group

switch:
  - platform: broadlink
    mac: !secret broadlink_bedroom_mac
    switches:
      - name: "Bedroom TV"
        command_on: 'JgCMAJGUEjgSOBE4EhMSExITEhMRFBE4EjgSOBETEhMSExITEhMSExE4EhMSExITEhMSExETEjgSExI4EjcSOBI4EjcSOBIABgaTlBI4EjgSNxITEhMSExITEhMROBI4EjgSExETEhMSExITEhMSNxITEhMSExITEhMSExE4EhMSOBI4ETgSOBI4ETgSAA0FAAAAAAAAAAAAAA=='
        command_off: 'JgCMAJGUEjgSOBE4EhMSExITEhMRFBE4EjgSOBETEhMSExITEhMSExE4EhMSExITEhMSExETEjgSExI4EjcSOBI4EjcSOBIABgaTlBI4EjgSNxITEhMSExITEhMROBI4EjgSExETEhMSExITEhMSNxITEhMSExITEhMSExE4EhMSOBI4ETgSOBI4ETgSAA0FAAAAAAAAAAAAAA=='
      
      - name: "Bedroom Tv Volume"
        command_on: "JgCgAJWSEg8SDxIPEg4TLxMvEg8SDxIwEjASMBIwEg8SDxIPEg4SkhIPEg8SDxIPEjASMBIwEg8SMBIvEy8SDxIPEg8SDxIwEg8SDxIPEjASAAcblpISDxIPEg8SDxIwEjASDxIPEi8TLxMvEjASDxIPEg8SDxKSEg8SDxIPEg8SLxMvEjASDxIwEjASMBIPEg8SDxIPEi8TDhMOEg8SMBIADQUAAAAAAAA="
        command_off: "JgCgAJSSEg8SDxIPEg8SLxMvEw4SDxIwEjASMBIwEg8SDxIPEg4SkhIPEg8SDxIPEg8SDxIPEjASMBIwEi8TDhMvEy8SMBIPEg8SDxIPEjASAAcblpISDxIPEg8SDxIwEi8TDhMOEy8SMBIwEjASDxIPEg8SDhKTEg8SDhMOEw4TDhIPEg8SMBIwEjASMBIPEjASMBIvEw4TDhIPEg8SMBIADQUAAAAAAAA="
      
      - name: "bedroom_tv_mute"
        command_on: "JgCgAJSSEg8SDhMOEg8SMBIwEg8SDxIwEjASMBIvEw4SDxMOEg8SkhIPEg8SDxIPEjASDxIPEg8SLxMvEjASDxIPEjASMBIwEg8SDxIPEi8TAAcclZISDxIPEg8SDxIvEjASDxIPEjASMBIwEjASDxIPEg4TDhKSEg8SDxIPEg8SMBIPEg8SDxIwEi8TLxIPEg8SMBIwEjASDxIPEg8SMBIADQUAAAAAAAA="  
        command_off: "JgCgAJSSEg8SDxIPEg8SMBIwEg8SDxIvEy8TLxIwEg8SDxIPEg4TkhIPEg8SDhMOEy8TDhIPEg8SMBIwEjASDxIPEi8TLxMvEg8SDxIPEjASAAcblpISDxIPEg8SDxIwEjASDxIOEy8TLxIwEjASDxIPEg8SDhKSEw4TDhMOEw4SMBIPEg8SDxIwEjASMBIPEg8SLxMvEjASDxIPEg8SMBIADQUAAAAAAAA="  
      
      - name: "Bedroom SoundBar" 
        command_on: "JgDwAJKUERAQERAREBEQMhAyEBEQERAyEDERMRExEBEQERAREBEQlBAREBEQERAREBEQERAREBEQMhAxEDIQERAyEDIQMhAyEBEQERAREDERAAcdlJQREBAREBEQERAyEDIQERAREDIQMRExEDIQERAREBEQERCUEBEQERAREBEQEREQEBEQERAxETEQMhAREDIQMhAyEDIQERAREBEQMhAABx2UlBEQEBEQERAREDIQMhAREBEQMhAyEDIQMg8REBIQEBAREJUQEBAREBIPERAREBEQERAREDIQMRExEBEQMhAyEDIQMhAREBEQERAyEAANBQAAAAAAAA=="
        command_off: "JgDwAJKUERAQERAREBEQMhAyEBEQERAyEDERMRExEBEQERAREBEQlBAREBEQERAREBEQERAREBEQMhAxEDIQERAyEDIQMhAyEBEQERAREDERAAcdlJQREBAREBEQERAyEDIQERAREDIQMRExEDIQERAREBEQERCUEBEQERAREBEQEREQEBEQERAxETEQMhAREDIQMhAyEDIQERAREBEQMhAABx2UlBEQEBEQERAREDIQMhAREBEQMhAyEDIQMg8REBIQEBAREJUQEBAREBIPERAREBEQERAREDIQMRExEBEQMhAyEDIQMhAREBEQERAyEAANBQAAAAAAAA=="

      - name: "AC Dumper"
        command_on: "JgBcAb48ExETEhISEjUTERM1EzUSEhISExETNRISEjYSNhISEjYSERM1EjUTNRM1EjUTERM1ExETERMREzUTNRI1ExISEhI1EzUTNRI1EzUTNRI1EzUTNRI1EzUTNRI1EzUTNRI1ExETEhISEhISEhISEzUSEr49ExETEhISEjUTERM1EzUSEhMRExISNRMREjYSNhMQEzUTERM1EjUTNRM1EjUTEhI1ExETERMREzUTNRI1ExISEhI1EzUTNRI1EzUTNRI1EzUTNRI1EzUTNRI1EzUTNBM1ExETERMSEhISEhISEjUTEr49ExETERMREzUTERM1EjYTERISEhISNhISEjYTNRESEzUSEhI1EzUTNRI1EzUTERM1EhITERMREzUSNRM1ExETERM1EzUSNRM1EzUSNRM1EzUSNRM1EzUSNRM1EzUSNRM1ExETERMRExETERMSEjUTEQABAAANBQAAAAAAAAAAAAA="
        command_off: "JgBcAcA7ExAUEBQQFDQUEBQ0ExETNBQREzQUEBQREzQUNBQ0ExETERQQFDQTNBQ0FBAUNBQQFBAUEBQ0FBAUNBM0FDQUEBQ0FDMUNBQ0FDMUNBQ0FDQUMxQ0FDQUMxQ0FDQUMxQ0FBAUEBQQFBEUMxQQFDQUEME7FBAUEBQQFDQUEBQzFRAUMxQQFDQUEBQQFDQUNBQzFBAVEBQQFDMUNBQ0FBAUMxUQFBAUEBQzFRAUMxQ0FDQUEBQzFTMUNBQ0FDMUNBQ0FDMUNBQ0FDMUNBQ0FDMUNBQ0FBAUEBQQFBAUNBQQFDMUEcA7FBAUEBQREzQUEBQ0FBAUNBMREzQUERMREzQUNBQ0ExETERMRFDQTNBQ0FBAUNBMRExEUEBQ0ExETNBQ0FDQTERQ0EzQUNBQ0EzQUNBQ0EzQUNBQ0EzQUNBQ0EzQUNBQ0ExEUEBQQFBAUNBQQFDMUEQABAAANBQAAAAAAAAAAAAA="

light:
  - platform: switch
    name: "Kids night lamp"
    entity_id: switch.sonoff_kids_night_lamp
  
  - platform: switch
    name: "Kitchen spotlights"
    entity_id: switch.sonoff_kitchen_spotlights
  
  - platform: switch 
    name: "Couch Lamp"
    entity_id: switch.sonoff_couch

  - platform: switch 
    name: "Bathroom light"
    entity_id: switch.bath_main_sonoff
 
  - platform: switch 
    name: "Bathroom mirror"
    entity_id: switch.bath_mirror_sonoff
  
  - platform: switch 
    name: "Dining Lights"
    entity_id: switch.dining_tuya

  - platform: switch 
    name: "Door Light"
    entity_id: switch.door_tuya
  
  - platform: switch 
    name: "Parents Bath main light"
    entity_id: switch.parents_bath_main_tuya

  - platform: switch 
    name: "Parents Bathroom mirror"
    entity_id:  switch.parent_bath_mirror_tuya

  - platform: switch 
    name: "Parents Bedrrom light"
    entity_id: switch.badroom_light
  
  - platform: switch 
    name: "Kitchen light"
    entity_id: switch.kitchen_light

climate:
  # - platform: smartir
  #   name: Bedroom AC
  #   unique_id: bedroom_ac
  #   device_code: 1181
  #   controller_data: remote.bedroom_remote
  #   temperature_sensor: sensor.sonoff_badroom_temperature
  #   humidity_sensor: sensor.sonoff_badroom_humidity
  #   power_sensor: binary_sensor.ac_power

  - platform: smartir
    name: Main AC
    unique_id: main_ac
    device_code: 1340
    controller_data: remote.living_room_remote
    temperature_sensor: sensor.sonoff_living_room_temperature
    humidity_sensor: sensor.sonoff_living_room_humidity
    power_sensor: binary_sensor.ac_power

  - platform: ekon
     # This currently unused:
    name: Main account
      # Specify the name and password for your account
    username: !secret yair_email
    password: !secret ekon_password
    # temperature_sensor: sensor.sonoff_living_room_temperature
    #humidity_sensor: sensor.sonoff_living_room_humidity
    base_url: https://www.activate-ac.com/
    ws_url: wss://www.activate-ac.com/v2
    ssl_ignore: True
    # ws_url: wss://www.activate-ac.com/v2
      # **UNTESTED** Alternative EKON tadiran server
      # base_url: https://www.airconet.xyz/
     
media_player:
  - platform: smartir
    name: Bedroom TV
    unique_id: bedroom_tv
    device_code: 1060
    controller_data: remote.bedroom_remote
    source_names:
      HDMI1: Amazon Fire TV
  
  - platform: smartir
    name: Receiver
    device_class: speaker
    unique_id: receiver
    device_code: 1121
    controller_data: remote.living_room_remote
 
  - platform: androidtv
    host: !secret amazon_fire_tv_host
    name: amazon_fire
    device_class: firetv
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037
    get_sources: true
    turn_on_command: "input keyevent 3"
    turn_off_command: "input keyevent 223"
    exclude_unnamed_apps: true
    apps:
        com.amazon.tv.launcher: "Fire TV"
        com.cellcom.cellcom_tv:  "Cellcom TV"
        com.plexapp.android: "Plex"
        com.netflix.ninja: "Netflix"
        com.amazon.firetv.youtube: "YouTube"
        com.stremio.one: "Stremio"
  
#   - platform: androidtv
#     host: !secret mi_box_host
#     name: mi_box
#     device_class: androidtv
#     adb_server_ip: 127.0.0.1
#     adb_server_port: 5037
#     get_sources: true
#     turn_on_command: "input keyevent 3"
#     turn_off_command: "input keyevent 223"
#     exclude_unnamed_apps: true
#     apps:
#         com.cellcom.cellcom_tv:  "Cellcom TV"
#         com.netflix.ninja: "Netflix"
#         com.stremio.one: "Stremio"
        
  - platform: samsungtv_tizen
    name: samsung_65
    api_key: !secret samsungtv_smart_api_key
    device_id: !secret samsungtv_smart_devcie_id
    mac: !secret samsungtv_mac
    host: !secret samsungtv_ip
    source_list: '{"MiBox": "ST_HDMI1", "Steam Link": "ST_HDMI2"}'
    app_list: '{"Netflix": "11101200001", "YouTube": "111299001912", "Spotify": "3201606009684", "Plex":"3201512006963"}'

  - platform: universal
    name: Bedroom Amazon TV
    children:
      - media_player.bedroom_tv
      - media_player.amazon_fire
    commands:
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.bedroom_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.bedroom_tv
      volume_up:
        service: media_player.volume_up
        data:
          entity_id: media_player.bedroom_tv
      volume_down:
        service: media_player.volume_down
        data:
          entity_id: media_player.bedroom_tv
      volume_mute:
        service: switch.turn_on
        data:
          entity_id: switch.bedroom_tv_mute
      select_source:
        service: media_player.select_source
        data:
          entity_id: media_player.amazon_fire
          source: '{{ source }}'
      volume_set:
        service: media_player.volume_set
        data:
          entity_id: media_player.bedroom_tv
          volume_level: '{{ volume_level }}'
    attributes:
      state: media_player.bedroom_tv
      is_volume_muted: switch.bedroom_tv_mute
      volume_level: media_player.bedroom_tv|volume_level
      source: media_player.amazon_fire|source
      source_list: media_player.amazon_fire|source_list

  # samsungtv_smart:
  #   - host: !secret samsungtv_ip
  #     api_key: !secret samsungtv_smart_api_key
  #     device_id: !secret samsungtv_smart_devcie_id
  #     name: Samsung_65
  #     mac: !secret samsungtv_mac
  #     source_list: '{"MiBox": "ST_HDMI1", "Steam Link": "ST_HDMI2"}'
  #     app_list: '{"Netflix": "11101200001", "YouTube": "111299001912", "Spotify": "3201606009684", "Plex":"3201512006963"}'

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret vacuum_xiaomi_miio_ip
    token: !secret vacuum_xiaomi_miio_token
    username: !secret vacuum_xiaomi_miio_username
    password: !secret vacuum_xiaomi_miio_password
    draw: ["all"]

vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_xiaomi_miio_ip
    token: !secret vacuum_xiaomi_miio_token
    
input_select:
  vacuum_room:
    name: Choose a room to clean
    options:
      - Select Input
      - Living Room
      - Kitchen
      - Kids Room
      - Office
      - Hallway
      - Bathroom
      - Laundry Room
      - Master Bedroom
      - Master Bathroom
    initial: Select Input
    
  bedroom_tv_source:
    name: Bedroom TV Sources
    options:
      - "TV"
      - "Amazon Fire TV"
      
  bedroom_soundbar_source:
    name: Bedroom SoundBar Sources
    options:
      - "Optical"
      - "Bluetooth"
      
sensor:
  - platform: template
    sensors:
      outdoor_temperature:
        friendly_name: "Temperature outside"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('weather.home', 'temperature') }}"

  - platform: waze_travel_time
    origin: zone.home
    destination: zone.yair_work
    name: Yair home to work
    region: 'IL'
  - platform: waze_travel_time
    origin: zone.home
    destination: zone.maggy_work
    name: Maggy home to work
    region: 'IL'
  - platform: waze_travel_time
    origin: zone.yair_work
    destination: zone.home
    name: Yair work to home
    region: 'IL'
  - platform: waze_travel_time
    origin: zone.maggy_work
    destination: zone.home
    name: Maggy work to home
    region: 'IL'
  - platform: command_line
    name: CPU Temp
    command: "/bin/cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "ºC"
    value_template: '{{ value | multiply(0.001) }}'
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
    - type: disk_free
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    
  - platform: ping
    hosts:
      yair_wifi: !secret yair_5t_host

python_script:


# logger:
#   default: info
#   logs:
#     homeassistant.components.python_scripts: debug
