esphome:
  name: balcony_shutter
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "maggyair"
  password: "avivTAl@"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Balcony Shutter Fallback Hotspot"
    password: "AVq9NVE9e8iX"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
